ARG BASE_IMAGE=gentoo/stage3:amd64-systemd
FROM ${BASE_IMAGE}

RUN echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf && \
    echo 'FEATURES="-pid-sandbox -ipc-sandbox -network-sandbox"' >> /etc/portage/make.conf && \
    echo "net-libs/nodejs npm" >> /etc/portage/package.use/nodejs && \
    emerge --sync && \
    emerge -u1vDN --quiet-build sys-apps/portage && \
    emerge -u1vDN --quiet-build dev-lang/perl app-admin/perl-cleaner && \
    perl-cleaner --all -- --quiet-build && \
    emerge -uvDN --with-bdeps=y --backtrack=50 --quiet-build @world && \
    emerge --noreplace --quiet-build dev-vcs/git dev-util/pkgdev dev-util/pkgcheck dev-util/github-cli dev-lang/go dev-lang/rust-bin app-misc/jq net-libs/nodejs && \
    npm install -g @anthropic-ai/claude-code
